project:
  type: book

book:
  title: "Machine learning for practical projects"
  author: "Ita cirovic Donev (FinMetrika d.o.o.)"
  date: "February 2024"
  page-navigation: true
  chapters:
    - index.qmd
    - docs/00_set_ml_project.qmd
    - docs/data/01_data.qmd
    - docs/data/02_data_processing.qmd
    - docs/data/04_data_sampling.qmd
    - docs/data/03_data_vizualization.qmd
    - docs/models/20_training.qmd
    - docs/30_utils.qmd
    #- references.qmd

#bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    code-summary: "show code"
    code-overflow: wrap
    code-copy: true
    #code-line-numbers: true
    highlight-style: breeze
    #code-line-numbers: true
    toc-depth: 4
    css: styles.css
  pdf:
    documentclass: report
    papersize: A4
    #lof: true
    #lot: true
    geometry:
      - top=10mm
      - left=10mm
      - right=30mm
      - bottom=15mm
      - heightrounded
    highlight-style: github
    fontfamily: libertinus
    colorlinks: true
  
#execute: 
#  freeze: auto
title-block-banner: false
title-block-style: default